# Generated by Django 3.1.1 on 2020-09-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecondTask', '0002_bill_classtype_groupbill_incomingbalance_outcomingbalance_turnover'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='class_of',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='SecondTask.classtype'),
        ),
        migrations.AddField(
            model_name='bill',
            name='file',
            field=models.ForeignKey(default='0', editable=False, on_delete=django.db.models.deletion.CASCADE, to='SecondTask.file'),
        ),
        migrations.AddField(
            model_name='classtype',
            name='file',
            field=models.ForeignKey(default='0', editable=False, on_delete=django.db.models.deletion.CASCADE, to='SecondTask.file'),
        ),
        migrations.AddField(
            model_name='groupbill',
            name='file',
            field=models.ForeignKey(default='0', editable=False, on_delete=django.db.models.deletion.CASCADE, to='SecondTask.file'),
        ),
        migrations.AddField(
            model_name='incomingbalance',
            name='file',
            field=models.ForeignKey(default='0', editable=False, on_delete=django.db.models.deletion.CASCADE, to='SecondTask.file'),
        ),
        migrations.AddField(
            model_name='outcomingbalance',
            name='file',
            field=models.ForeignKey(default='0', editable=False, on_delete=django.db.models.deletion.CASCADE, to='SecondTask.file'),
        ),
        migrations.AddField(
            model_name='turnover',
            name='file',
            field=models.ForeignKey(default='0', editable=False, on_delete=django.db.models.deletion.CASCADE, to='SecondTask.file'),
        ),
        migrations.AlterField(
            model_name='incomingbalance',
            name='active',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='incomingbalance',
            name='passive',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='outcomingbalance',
            name='active',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='outcomingbalance',
            name='passive',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='credit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='turnover',
            name='debet',
            field=models.FloatField(),
        ),
    ]
