# Generated by Django 3.1.1 on 2020-09-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecondTask', '0005_auto_20200916_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingbalance',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='incomingbalance',
            name='class_of',
        ),
        migrations.RemoveField(
            model_name='outcomingbalance',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='outcomingbalance',
            name='class_of',
        ),
        migrations.RemoveField(
            model_name='turnover',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='turnover',
            name='class_of',
        ),
    ]
